Adds @powerpages Integration
microsoft/powerplatform-vscode pull request #994
Opened 2024-07-09 11:16 UTC by amitjoshi438

**@powerpages integration is currently behind a WHEN clause and it's set to FALSE by default**

This pull request introduces several changes to improve the Power Pages Copilot feature in the application. The most significant changes include adding new localization strings, enabling API proposals in the `package.json` file, and creating a new chat participant for Power Pages. Additionally, the OrgChangeNotifier class has been updated to include the extension context, and a new utility function has been added to create chat participants.

Localization:

* [`l10n/bundle.l10n.json`](diffhunk://#diff-829b512e02461234524c007941f3260e67a43b109f48bedf257ab8e8033cc527R70-R73): Added new localization strings for user prompts and error messages.
* [`loc/translations-export/vscode-powerplatform.xlf`](diffhunk://#diff-62401b58ce452f2686a1cbf6945a0bf5bb33bf35151df029524ced13ada25794R19-R21): Added translations for the new localization strings. [[1]](diffhunk://#diff-62401b58ce452f2686a1cbf6945a0bf5bb33bf35151df029524ced13ada25794R19-R21) [[2]](diffhunk://#diff-62401b58ce452f2686a1cbf6945a0bf5bb33bf35151df029524ced13ada25794R35-R37) [[3]](diffhunk://#diff-62401b58ce452f2686a1cbf6945a0bf5bb33bf35151df029524ced13ada25794R84-R86) [[4]](diffhunk://#diff-62401b58ce452f2686a1cbf6945a0bf5bb33bf35151df029524ced13ada25794R283-R286)

Configuration:

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R104-R108): Enabled API proposals related to chat participants and language models. Also, added configuration for the Power Pages chat participant and a new experimental setting for enabling the Power Pages integration. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R104-R108) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R120-R129) [[3]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R398-R402)

Codebase improvements:

* [`src/client/extension.ts`](diffhunk://#diff-70fa1444b963acf260ba9443bca34c5f078ec0f23bbc3eb5cb5eaa00dc664baaL217-R217): Updated the `activate` function to pass the extension context to the `createOrgChangeNotifierInstance` method.
* [`src/client/lib/PacActivityBarUI.ts`](diffhunk://#diff-367f4c2df27cd65dad8a96ff1497027c82dcde8723c93e4356a147f20e1de86fR12): Imported the `PowerPagesChatParticipant` class and updated the `RegisterPanels` function to include the Power Pages chat participant. [[1]](diffhunk://#diff-367f4c2df27cd65dad8a96ff1497027c82dcde8723c93e4356a147f20e1de86fR12) [[2]](diffhunk://#diff-367f4c2df27cd65dad8a96ff1497027c82dcde8723c93e4356a147f20e1de86fR24-R32)
* [`src/common/OrgChangeNotifier.ts`](diffhunk://#diff-726acaa16005d3b4352314fee8dbc4879a53dfb2d3e22bd08ce85e7ef9a311a8R21-R35): Modified the `OrgChangeNotifier` class to include the extension context and updated the `createOrgChangeNotifierInstance` method to pass the extension context.
* [`src/common/chat-participants/ChatParticipantUtils.ts`](diffhunk://#diff-776fde87682985e6a43d5038599a6b92ad985e4a539979d54a5b87a6b5835dfaR1-R10): Added a new utility function to create chat participants.
* [`src/common/chat-participants/powerpages/PowerPagesChatParticipant.ts`](diffhunk://#diff-885f58fd5bd7ee590ddae0f7854d056026aff9b576864e07f61887fb7586da29R1-R189): Created a new chat participant for Power Pages. This class handles chat requests, initializes organization details, and handles organization change events.

2024-07-09 11:33 UTC, tyaginidhi requested changes

2024-07-09 11:33 UTC, tyaginidhi commented on src/common/utilities/OrgHandlerUtils.ts
> +import { PAC_SUCCESS } from '../copilot/constants';
lets not take dependency in common from copilot

2024-07-09 11:33 UTC, tyaginidhi commented on src/common/utilities/OrgHandlerUtils.ts
> +import { PacWrapper } from '../../client/pac/PacWrapper';
at some point we should consider moving this logic to common - that will keep referencing flow sorted. BUT see if we can atleast still remove this reference in common module. Copilot should be the only exception till we figure long term arrangement.

2024-07-09 11:33 UTC, tyaginidhi commented on src/common/chat-participants/powerpages/PowerPagesChatParticipantUtils.ts
> +import { ITelemetry } from "../../../client/telemetry/ITelemetry";
check references here too

2024-07-10 09:55 UTC, tyaginidhi approved these changes

2024-07-11 03:46 UTC, ritikramuka approved these changes

2024-07-11 08:20 UTC, merged